<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260303182323 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_880E0D76E7927C74 ON admin (email)');
        $this->addSql('CREATE TABLE competency (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, attribute VARCHAR(255) NOT NULL, weight INT NOT NULL, active BOOLEAN NOT NULL, level_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_80D534305FB14BA7 ON competency (level_id)');
        $this->addSql('CREATE TABLE evaluation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, progress INT NOT NULL, competencies JSON NOT NULL, person_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1323A575217BBB47 ON evaluation (person_id)');
        $this->addSql('CREATE TABLE level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, percentage INT NOT NULL, speciality_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9AEACC133B5A08D7 ON level (speciality_id)');
        $this->addSql('CREATE TABLE person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, evaluator INT NOT NULL, active BOOLEAN NOT NULL, level_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_34DCD1765FB14BA7 ON person (level_id)');
        $this->addSql('CREATE TABLE speciality (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE competency ADD CONSTRAINT FK_80D534305FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575217BBB47 FOREIGN KEY (person_id) REFERENCES person (id)');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC133B5A08D7 FOREIGN KEY (speciality_id) REFERENCES speciality (id)');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD1765FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE competency DROP CONSTRAINT FK_80D534305FB14BA7');
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A575217BBB47');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC133B5A08D7');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD1765FB14BA7');
        $this->addSql('DROP TABLE admin');
        $this->addSql('DROP TABLE competency');
        $this->addSql('DROP TABLE evaluation');
        $this->addSql('DROP TABLE level');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE speciality');
        $this->addSql('DROP TABLE type');
    }
}
